### ISSUE TITLE
Connections closing and timing out inserting/deleting data

### ISSUE THREAD

**Issue by stickperson** [docker-library/cassandra#101]
First off, here's my setup:
- running docker for mac
- single cassandra instance running in a container named "cassandra"
- running a script that imports/deletes data from cassandra (using the [python driver](https://github.com/datastax/python-driver)) in another container. This container and the cassandra container are running in the same network
- the table has an index, but at the time that value is the same for all entries

The gist of the import/delete code goes something like this:

```
class Controller(object):
    def __init__(self):
        self.cluster = Cluster(['cassandra']) # cassandra is running in a container named cassandra
        self.session = self.cluster.connect('mykeyspace')

    def insert_params_gen(self, fname):
        # iterates through a file (fname), yields data for every line

    def insert_into_cassandra(self, fname):
        query = ('INSERT INTO mytable (mykey, indexed_key) VALUES (?, ?)')
        prepared = self.session.prepare(query)
        prepared.consistency_level = ConsistencyLevel.QUORUM
        params_gen = self.insert_params_gen(fname)
        execute_concurrent_with_args(self.session, prepared, params_gen, concurrency=50)

    def delete_param_gen(self, results):
        for r in results:
            yield [r.mykey]

    def delete_by_index(self, value):
        query = "SELECT mykey from mytable where indexed_key = '%s'" % value
        res = self.session.execute(query)
        delete_query = "DELETE from mytable where mykey = ?"
        prepared = self.session.prepare(delete_query)
        prepared.consistency_level = ConsistencyLevel.QUORUM
        params_gen = self.delete_param_gen(res)
        execute_concurrent_with_args(self.session, prepared, params_gen, concurrency=50)
```

Let's start with the problems that arise during insertion. I've been playing with the `concurrency` kwarg which doesn't really seem to have much effect. Some insertions will be successful (sometimes 500, sometimes 10k), but then the script eventually crashes. Here are the logs from the container with the script:

```
[2017-02-28 19:09:57,531] [DEBUG] [cassandra.connection] Sending options message heartbeat on idle connection (139984127591480) 172.20.0.2
[2017-02-28 19:10:27,532] [WARNING] [cassandra.connection] Heartbeat failed for connection (139984127591480) to 172.20.0.2
[2017-02-28 19:10:27,532] [DEBUG] [cassandra.connection] Defuncting connection (139984127591480) to 172.20.0.2: errors=Connection heartbeat timeout after 30 seconds, last_host=172.20.0.2
[2017-02-28 19:10:27,533] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (139984127591480) to 172.20.0.2
[2017-02-28 19:10:27,533] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:10:27,533] [DEBUG] [cassandra.cluster] [control connection] Attempting to reconnect
[2017-02-28 19:10:27,534] [DEBUG] [cassandra.cluster] [control connection] Opening new connection to 172.20.0.2
[2017-02-28 19:10:27,537] [DEBUG] [cassandra.connection] Not sending options message for new connection(139984126691816) to 172.20.0.2 because compression is disabled and a cql version was not specified
[2017-02-28 19:10:27,537] [DEBUG] [cassandra.connection] Sending StartupMessage on <AsyncoreConnection(139984126691816) 172.20.0.2:9042>
[2017-02-28 19:10:27,538] [DEBUG] [cassandra.connection] Sent StartupMessage on <AsyncoreConnection(139984126691816) 172.20.0.2:9042>
[2017-02-28 19:10:27,543] [DEBUG] [cassandra.connection] Sending options message heartbeat on idle connection (139984167188912) 172.20.0.2
[2017-02-28 19:10:27,544] [DEBUG] [cassandra.cluster] [control connection] Attempting to reconnect
[2017-02-28 19:10:27,544] [DEBUG] [cassandra.cluster] [control connection] Opening new connection to 172.20.0.2
[2017-02-28 19:10:27,545] [DEBUG] [cassandra.connection] Not sending options message for new connection(139984127670648) to 172.20.0.2 because compression is disabled and a cql version was not specified
[2017-02-28 19:10:27,545] [DEBUG] [cassandra.connection] Sending StartupMessage on <AsyncoreConnection(139984127670648) 172.20.0.2:9042>
[2017-02-28 19:10:27,546] [DEBUG] [cassandra.connection] Sent StartupMessage on <AsyncoreConnection(139984127670648) 172.20.0.2:9042>
[2017-02-28 19:10:32,535] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (139984126691816) to 172.20.0.2
[2017-02-28 19:10:32,536] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:10:32,536] [DEBUG] [cassandra.connection] Connection to 172.20.0.2 was closed during the startup handshake
[2017-02-28 19:10:32,538] [WARNING] [cassandra.cluster] [control connection] Error connecting to 172.20.0.2:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2623, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:47899)
  File "cassandra/cluster.py", line 2645, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:48416)
  File "cassandra/cluster.py", line 1119, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:15085)
  File "cassandra/connection.py", line 333, in cassandra.connection.Connection.factory (cassandra/connection.c:5790)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
[2017-02-28 19:10:32,545] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (139984127670648) to 172.20.0.2
[2017-02-28 19:10:32,545] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:10:32,545] [DEBUG] [cassandra.connection] Connection to 172.20.0.2 was closed during the startup handshake
[2017-02-28 19:10:32,545] [WARNING] [cassandra.cluster] [control connection] Error connecting to 172.20.0.2:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2623, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:47899)
  File "cassandra/cluster.py", line 2645, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:48416)
  File "cassandra/cluster.py", line 1119, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:15085)
  File "cassandra/connection.py", line 333, in cassandra.connection.Connection.factory (cassandra/connection.c:5790)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
[2017-02-28 19:10:33,030] [INFO] [root] Success 18820
[2017-02-28 19:10:33,030] [INFO] [root] Success 18821
[2017-02-28 19:10:33,031] [ERROR] [root] Exception inserting data into cassandra
Traceback (most recent call last):
  File "load_cassandra.py", line 54, in run
    controller.insert_into_cassandra(filename)
  File "load_cassandra.py", line 141, in insert_into_cassandra
    for success, result in results:
  File "cassandra/concurrent.py", line 177, in _results (cassandra/concurrent.c:4856)
  File "cassandra/concurrent.py", line 186, in cassandra.concurrent.ConcurrentExecutorGenResults._results (cassandra/concurrent.c:4622)
  File "cassandra/concurrent.py", line 165, in cassandra.concurrent._ConcurrentExecutor._raise (cassandra/concurrent.c:3745)
cassandra.WriteTimeout: Error from server: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 0 responses." info={'consistency': 'QUORUM', 'required_responses': 1, 'received_responses': 0}
[2017-02-28 19:10:33,173] [DEBUG] [cassandra.connection] Received options response on connection (139984167188912) from 172.20.0.2
[2017-02-28 19:10:33,175] [DEBUG] [cassandra.cluster] Shutting down Cluster Scheduler
[2017-02-28 19:10:33,176] [DEBUG] [cassandra.cluster] Shutting down control connection
[2017-02-28 19:10:33,178] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (139984167188912) to 172.20.0.2
[2017-02-28 19:10:33,178] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:10:33,178] [DEBUG] [cassandra.pool] Defunct or closed connection (139984167188912) returned to pool, potentially marking host 172.20.0.2 as down
```

During that process, I see several messages in the cassandra logs that are similar to: `Out of 1 commit log syncs over the past 0s with average duration of 10636.00ms, 1 have exceeded the configured commit interval by an average of 636.00ms`

Running `docker inspect cassandra` during the load, I see that the cassandra container fluctuates between 30%-~120% cpu.

For the delete operation, `delete_param_gen` yields 5k results (there are more than 5k entries in the table) and then things stop. The script logs look like:

```
[2017-02-28 19:48:44,106] [DEBUG] [cassandra.connection] Sending options message heartbeat on idle connection (140209039037944) 172.20.0.2
[2017-02-28 19:48:44,106] [DEBUG] [cassandra.connection] Sending options message heartbeat on idle connection (140209038978128) 172.20.0.2
[2017-02-28 19:49:14,107] [WARNING] [cassandra.connection] Heartbeat failed for connection (140209039037944) to 172.20.0.2
[2017-02-28 19:49:44,110] [WARNING] [cassandra.connection] Heartbeat failed for connection (140209038978128) to 172.20.0.2
[2017-02-28 19:49:44,113] [DEBUG] [cassandra.connection] Defuncting connection (140209039037944) to 172.20.0.2: errors=Connection heartbeat timeout after 30 seconds, last_host=172.20.0.2
[2017-02-28 19:49:44,113] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (140209039037944) to 172.20.0.2
[2017-02-28 19:49:44,113] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:49:44,117] [DEBUG] [cassandra.pool] Defunct or closed connection (140209039037944) returned to pool, potentially marking host 172.20.0.2 as down
[2017-02-28 19:49:44,117] [DEBUG] [cassandra.pool] Replacing connection (140209039037944) to 172.20.0.2
[2017-02-28 19:49:44,118] [DEBUG] [cassandra.connection] Defuncting connection (140209038978128) to 172.20.0.2: errors=Connection heartbeat timeout after 30 seconds, last_host=172.20.0.2
[2017-02-28 19:49:44,119] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (140209038978128) to 172.20.0.2
[2017-02-28 19:49:44,121] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:49:44,125] [DEBUG] [cassandra.connection] Not sending options message for new connection(140208776709904) to 172.20.0.2 because compression is disabled and a cql version was not specified
[2017-02-28 19:49:44,125] [DEBUG] [cassandra.connection] Sending StartupMessage on <AsyncoreConnection(140208776709904) 172.20.0.2:9042>
[2017-02-28 19:49:44,126] [DEBUG] [cassandra.connection] Sent StartupMessage on <AsyncoreConnection(140208776709904) 172.20.0.2:9042>
[2017-02-28 19:49:49,119] [DEBUG] [cassandra.io.asyncorereactor] Closing connection (140208776709904) to 172.20.0.2
[2017-02-28 19:49:49,120] [DEBUG] [cassandra.io.asyncorereactor] Closed socket to 172.20.0.2
[2017-02-28 19:49:49,120] [DEBUG] [cassandra.connection] Connection to 172.20.0.2 was closed during the startup handshake
[2017-02-28 19:49:49,120] [WARNING] [cassandra.pool] Failed reconnecting 172.20.0.2. Retrying.
```

and I see the following in the cassandra logs during that period:
```
WARN  19:47:45 Read 5000 live rows and 1226 tombstone cells for query SELECT * FROM mykeyspace.mytable WHERE source = test AND  LIMIT 5000 (see tombstone_warn_threshold)
WARN  19:47:58 Out of 24 commit log syncs over the past 134s with average duration of 5565.17ms, 3 have exceeded the configured commit interval by an average of 14885.00ms
```

I also tried running everything outside of docker with a local install of cassandra. The insertions seemed to go a bit better but were still unreliable. I got the same problems with deletions though.

A couple questions I have:

- What's going on here? As I mentioned, I tried tweaking `concurrency`, but that didn't really seem to have any effect. I'm not really sure where to start debugging.
- is there any connection between the `concurrency` kwarg in `execute_concurrent_with_args` and the `concurrent_writes` config in `cassandra.yaml`? Furthermore, how does this come into play when using multiple processes as the [performance] (https://datastax.github.io/python-driver/performance.html) section of the python driver docs suggests?

**Edit**: I noticed a couple more things in the logs. On startup of the cassandra container I see `Cassandra server running in degraded mode. Is swap disabled? : false,  Address space adequate? : true,  nofile limit adequate? : true, nproc limit adequate? : true`. I tried running with `--memory 2G` and `--memory_swap 2G` but still see the same message.

Here's some more output from the cassandra logs when the `WriteTimeout` error occurs:

```
INFO  22:24:47 Node /172.20.0.2 state jump to NORMAL
INFO  22:24:47 Waiting for gossip to settle before accepting client requests...
INFO  22:24:55 No gossip backlog; proceeding
INFO  22:24:56 Netty using native Epoll event loop
INFO  22:24:56 Using Netty Version: [netty-buffer=netty-buffer-4.0.39.Final.38bdf86, netty-codec=netty-codec-4.0.39.Final.38bdf86, netty-codec-haproxy=netty-codec-haproxy-4.0.39.Final.38bdf86, netty-codec-http=netty-codec-http-4.0.39.Final.38bdf86, netty-codec-socks=netty-codec-socks-4.0.39.Final.38bdf86, netty-common=netty-common-4.0.39.Final.38bdf86,
-4.0.39.Final.38bdf86, netty-tcnative=netty-tcnative-1.1.33.Fork19.fe4816e, netty-transport=netty-transport-4.0.39.Final.38bdf86, netty-transport-native-epoll=netty-transport-native-epoll-4.0.39.Final.38bdf86, netty-transport-rxtx=netty-transport-rxtx-4.0.39.Final.38bdf86, netty-transport-sctp=netty-transport-sctp-4.0.39.Final.38bdf86, netty-transport-u
39.Final.38bdf86]
INFO  22:24:56 Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
INFO  22:24:56 Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it
INFO  22:24:57 Scheduling approximate time-check task with a precision of 10 milliseconds
INFO  22:25:41 Handshaking version with /172.20.0.2
INFO  22:27:03 MUTATION messages were dropped in last 5000 ms: 1 for internal timeout and 0 for cross node timeout. Mean internal dropped latency: 76525 ms and Mean cross-node dropped latency: 0 ms
INFO  22:27:03 Pool Name                    Active   Pending      Completed   Blocked  All Time Blocked
INFO  22:27:03 MutationStage                     9         0            675         0                 0

INFO  22:27:03 ViewMutationStage                 0         0              0         0                 0

INFO  22:27:03 ReadStage                         0         0             24         0                 0

INFO  22:27:03 RequestResponseStage              0         0              1         0                 0

INFO  22:27:03 ReadRepairStage                   0         0              0         0                 0

INFO  22:27:03 CounterMutationStage              0         0              0         0                 0

INFO  22:27:03 MiscStage                         0         0              0         0                 0

INFO  22:27:03 CompactionExecutor                0         0             48         0                 0

INFO  22:27:03 MemtableReclaimMemory             0         0             17         0                 0

INFO  22:27:03 PendingRangeCalculator            0         0              1         0                 0

INFO  22:27:03 GossipStage                       0         0              0         0                 0

INFO  22:27:03 SecondaryIndexManagement          0         0              0         0                 0

INFO  22:27:03 HintsDispatcher                   0         0              0         0                 0

INFO  22:27:03 MigrationStage                    0         0              0         0                 0

INFO  22:27:03 MemtablePostFlush                 0         0             40         0                 0

INFO  22:27:03 PerDiskMemtableFlushWriter_0         0         0             17         0                 0

INFO  22:27:03 ValidationExecutor                0         0              0         0                 0

INFO  22:27:03 Sampler                           0         0              0         0                 0

INFO  22:27:03 MemtableFlushWriter               0         0             17         0                 0

INFO  22:27:03 InternalResponseStage             0         0              0         0                 0

INFO  22:27:03 AntiEntropyStage                  0         0              0         0                 0

INFO  22:27:03 CacheCleanupExecutor              0         0              0         0                 0

INFO  22:27:03 Native-Transport-Requests        10         5            163         0                 0


INFO  22:27:03 CompactionManager                 0         0
INFO  22:27:04 MessagingService                n/a       0/0
INFO  22:27:04 Cache Type                     Size                 Capacity               KeysToSave
INFO  22:27:04 KeyCache                       1184                 50331648                      all
INFO  22:27:04 RowCache                          0                        0                      all
INFO  22:27:04 Table                       Memtable ops,data
INFO  22:27:04 system_distributed.parent_repair_history                 0,0
INFO  22:27:04 system_distributed.repair_history                 0,0
INFO  22:27:04 system_distributed.view_build_status                 0,0
INFO  22:27:04 system.compaction_history               2,384
INFO  22:27:04 system.hints                              0,0
INFO  22:27:04 system.schema_aggregates                  0,0
INFO  22:27:04 system.IndexInfo                          0,0
INFO  22:27:04 system.schema_columnfamilies                 0,0
INFO  22:27:04 system.schema_triggers                    0,0
INFO  22:27:04 system.size_estimates                 20,1255
INFO  22:27:04 system.schema_functions                   0,0
INFO  22:27:04 system.paxos                              0,0
INFO  22:27:04 system.views_builds_in_progress                 0,0
INFO  22:27:04 system.built_views                        0,0
INFO  22:27:04 system.peer_events                        0,0
INFO  22:27:04 system.range_xfers                        0,0
INFO  22:27:04 system.peers                              0,0
INFO  22:27:04 system.batches                            0,0
INFO  22:27:04 system.schema_keyspaces                   0,0
INFO  22:27:04 system.schema_usertypes                   0,0
INFO  22:27:04 system.local                              0,0
INFO  22:27:04 system.sstable_activity                10,157
INFO  22:27:04 system.available_ranges                   0,0
INFO  22:27:04 system.batchlog                           0,0
INFO  22:27:04 system.schema_columns                     0,0
INFO  22:27:04 system_schema.columns               171,26295
INFO  22:27:04 system_schema.types                      2,16
INFO  22:27:04 system_schema.indexes                    2,16
INFO  22:27:04 system_schema.keyspaces                 4,242
INFO  22:27:04 system_schema.dropped_columns                2,16
INFO  22:27:04 system_schema.aggregates                 2,16
INFO  22:27:04 system_schema.triggers                   2,16
INFO  22:27:04 system_schema.tables                 27,17400
INFO  22:27:04 system_schema.views                      2,16
INFO  22:27:04 system_schema.functions                  2,16
INFO  22:27:04 system_auth.roles                         0,0
INFO  22:27:04 system_auth.role_members                  0,0
INFO  22:27:04 system_auth.resource_role_permissons_index                 0,0
INFO  22:27:04 system_auth.role_permissions                 0,0
INFO  22:27:04 mykeyspace.mykey                        88,11381257
INFO  22:27:04 system_traces.sessions                    0,0
INFO  22:27:04 system_traces.events                      0,0
```

**Edit 2**: These problems occur only when inserting a data that has a `blob` field of about 80kb each. I tried including my own cassandra.yaml file with `write_request_timeout_in_ms` increased to 10000, but that did not work. If I edit my script and just put a simple string in the `blob` field instead everything works smoothly.

**Comment by yosifkit** [comment]
Initially, I would guess to make sure that you are __not__ using a volume mount to the host (`docker run -v /Users/myuser/cass-data/:/var/lib/cassandra/ --name cassandra cassandra`), since they have performance issues on "Docker for Mac".

> I also tried running everything outside of docker with a local install of cassandra. The insertions seemed to go a bit better but were still unreliable. I got the same problems with deletions though.

But since is also occurring outside the containerization, then this is not anything specific to the container image.  This would be better discussed in one of many options mentioned on https://academy.datastax.com/community-forums-support.

**Comment by stickperson** [comment]
@yosifkit Ah, I was unaware of the issues using volumes with docker for mac. Initial tests without a volume have been promising. Thanks for the help.
