### ISSUE TITLE
Not enough space for compaction messages, cassandra refusing connections.

### ISSUE THREAD

**Issue by lhosking** [docker-library/cassandra#103]
Hi, I am having trouble loading data into cassandra.  The issue occurs while loading from another container on the same network using the cassandra python driver.  

My environment is Docker for mac Version 17.03.1-ce-mac5 (16048), with everything running locally on this instance of Docker (the cassandra container is called _cassandra_).

The errors becomes apparent when all connected containers are unable to connect to cassandra. `docker logs cassandra` shows:

```INFO  [Service Thread] 2017-04-14 02:43:36,566 GCInspector.java:284 - ConcurrentMarkSweep GC in 438ms.  CMS Old Gen: 608870096 -> 332637976; Par Eden Space: 4288 -> 166629640;
INFO  [IndexSummaryManager:1] 2017-04-14 02:46:10,166 IndexSummaryRedistribution.java:75 - Redistributing index summaries
WARN  [CompactionExecutor:16] 2017-04-14 03:29:03,936 CompactionTask.java:94 - insufficient space to compact all requested files. 3318.432MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1253-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1279-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1304-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1329-big-Data.db')
WARN  [CompactionExecutor:16] 2017-04-14 03:29:03,940 CompactionTask.java:353 - Not enough space for compaction, 3318.432MB estimated.  Reducing scope.
ERROR [MemtablePostFlush:3] 2017-04-14 03:30:50,708 CassandraDaemon.java:229 - Exception in thread Thread[MemtablePostFlush:3,5,main]
org.apache.cassandra.io.FSWriteError: java.io.IOException: No space left on device
    at org.apache.cassandra.io.util.SequentialWriter.flushData(SequentialWriter.java:227) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.util.SequentialWriter.doFlush(SequentialWriter.java:191) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.util.SequentialWriter.syncInternal(SequentialWriter.java:184) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.util.SequentialWriter$TransactionalProxy.doPrepare(SequentialWriter.java:79) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.finish(Transactional.java:184) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.util.SequentialWriter.finish(SequentialWriter.java:382) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.sstable.format.big.BigTableWriter.writeMetadata(BigTableWriter.java:405) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.sstable.format.big.BigTableWriter.access$300(BigTableWriter.java:53) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.sstable.format.big.BigTableWriter$TransactionalProxy.doPrepare(BigTableWriter.java:368) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.sstable.format.SSTableWriter.prepareToCommit(SSTableWriter.java:281) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.io.sstable.SimpleSSTableMultiWriter.prepareToCommit(SimpleSSTableMultiWriter.java:101) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.db.ColumnFamilyStore$Flush.flushMemtable(ColumnFamilyStore.java:1153) ~[apache-cassandra-3.10.jar:3.10]
    at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1086) ~[apache-cassandra-3.10.jar:3.10]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
    at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:79) [apache-cassandra-3.10.jar:3.10]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.io.IOException: No space left on device
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_121]
    at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[na:1.8.0_121]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_121]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_121]
    at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[na:1.8.0_121]
    at org.apache.cassandra.io.util.SequentialWriter.flushData(SequentialWriter.java:222) ~[apache-cassandra-3.10.jar:3.10]
    ... 18 common frames omitted
ERROR [MemtablePostFlush:3] 2017-04-14 03:30:50,715 StorageService.java:427 - Stopping gossiper
WARN  [MemtablePostFlush:3] 2017-04-14 03:30:50,716 StorageService.java:318 - Stopping gossip by operator request
INFO  [MemtablePostFlush:3] 2017-04-14 03:30:50,716 Gossiper.java:1506 - Announcing shutdown
INFO  [MemtablePostFlush:3] 2017-04-14 03:30:50,718 StorageService.java:2248 - Node /172.18.0.3 state jump to shutdown
ERROR [MemtablePostFlush:3] 2017-04-14 03:30:52,721 StorageService.java:437 - Stopping native transport
INFO  [MemtablePostFlush:3] 2017-04-14 03:30:52,727 Server.java:176 - Stop listening for CQL clients
WARN  [CompactionExecutor:15] 2017-04-14 03:30:53,302 CompactionTask.java:94 - insufficient space to compact all requested files. 16538.049MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-809-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1143-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-537-big-Data.db')
WARN  [CompactionExecutor:15] 2017-04-14 03:30:53,302 CompactionTask.java:353 - Not enough space for compaction, 16538.049MB estimated.  Reducing scope.
WARN  [CompactionExecutor:15] 2017-04-14 03:30:53,302 CompactionTask.java:94 - insufficient space to compact all requested files. 13177.741MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1143-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-537-big-Data.db')
WARN  [CompactionExecutor:15] 2017-04-14 03:30:53,302 CompactionTask.java:353 - Not enough space for compaction, 13177.741MB estimated.  Reducing scope.
WARN  [CompactionExecutor:15] 2017-04-14 03:30:53,303 CompactionTask.java:94 - insufficient space to compact all requested files. 9833.936MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1143-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-537-big-Data.db')
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,226 CompactionTask.java:94 - insufficient space to compact all requested files. 13346.665MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-809-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1384-big-Data.db')
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,227 CompactionTask.java:353 - Not enough space for compaction, 13346.665MB estimated.  Reducing scope.
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,227 CompactionTask.java:94 - insufficient space to compact all requested files. 9986.357MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1384-big-Data.db')
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,228 CompactionTask.java:353 - Not enough space for compaction, 9986.357MB estimated.  Reducing scope.
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,228 CompactionTask.java:94 - insufficient space to compact all requested files. 6642.552MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1384-big-Data.db')
WARN  [CompactionExecutor:16] 2017-04-14 03:40:24,228 CompactionTask.java:353 - Not enough space for compaction, 6642.552MB estimated.  Reducing scope.
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,118 CompactionTask.java:94 - insufficient space to compact all requested files. 13346.665MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-809-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1385-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db')
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,119 CompactionTask.java:353 - Not enough space for compaction, 13346.665MB estimated.  Reducing scope.
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,119 CompactionTask.java:94 - insufficient space to compact all requested files. 9986.357MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1385-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-945-big-Data.db')
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,119 CompactionTask.java:353 - Not enough space for compaction, 9986.357MB estimated.  Reducing scope.
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,119 CompactionTask.java:94 - insufficient space to compact all requested files. 6642.552MB required, BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-716-big-Data.db'), BigTableReader(path='/var/lib/cassandra/data/aaaa/bbb-777e613020b511e7b63f51b56621147b/mc-1385-big-Data.db')
WARN  [CompactionExecutor:15] 2017-04-14 03:44:46,120 CompactionTask.java:353 - Not enough space for compaction, 6642.552MB estimated.  Reducing scope.
INFO  [IndexSummaryManager:1] 2017-04-14 03:46:10,215 IndexSummaryRedistribution.java:75 - Redistributing index summaries
```

There is also a warning in the startup messages:

```
WARN  [main] 2017-04-14 01:46:05,416 DatabaseDescriptor.java:540 - Only 53.143GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
```

I have cassandra using a volume specified in docker-compose.yml:

```
... 
  cassandra:
    container_name: cassandra
    ...
    volumes:
      - cassandra_data:/var/lib/cassandra
...
...
volumes:
  cassandra_data:
```

I am not aware of any size limitation set for Docker or this container. There is plenty of space on the local drive.

```
$ docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              37                  6                   5.261 GB            4.728 GB (89%)
Containers          6                   6                   123.5 MB            0 B (0%)
Local Volumes       16                  2                   38.65 GB            3.032 GB (7%)
```

```
$ df -h
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1     465Gi  146Gi  319Gi    32% 1100625 4293866654    0%   /
devfs          188Ki  188Ki    0Bi   100%     653          0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /home
```

Any thoughts?

**Comment by yosifkit** [comment]
So, from my quick research.

- It looks like your Cassandra database is ~`35.618 GB` (`38.65 − 3.032` from the size of your volumes)
  - could be less since you do have 2 active volumes so there is a second container with a volume
- if you're using SizeTieredCompaction, "a compaction will require 2 times of the on-disk space used for SSTables" http://stackoverflow.com/a/33433755
- in Docker for Mac "the disk is a 64GB Sparse Image that will expand on demand" https://forums.docker.com/t/no-space-left-on-device-error/10894/2

So, you could try the suggestion on the stackoverflow issue and switch to "LeveledCompactionStrategy" or see if you can increase the size of the VM disk used by Docker for Mac.
