### ISSUE TITLE
Can't connect to cassandra from cqlsh.

### ISSUE THREAD

**Issue by PiotrJustyna** [docker-library/cassandra#175]
Thanks for putting this together, that's a lot of great work 👏

Following the "How to use this image" [document](https://hub.docker.com/_/cassandra?tab=description/) I find it difficult to execute this step: "Connect to Cassandra from cqlsh". Full error and steps taken below:

Platform: windows 10
Docker version: 18.09.2

Sequence of commands executed:

1. `docker network create testnetwork`
2. `docker run --name some-cassandra --network testnetwork cassandra:3.0.18` (`-d` flag omitted)
3.  `docker run --name some-cassandra2 --network testnetwork -e CASSANDRA_SEEDS=some-cassandra cassandra:3.0.18` (`-d` flag omitted)
4. `docker run -it --rm cassandra cqlsh some-cassandra`

Error:

```
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 2443, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/usr/bin/cqlsh.py", line 2421, in main
    encoding=options.encoding)
  File "/usr/bin/cqlsh.py", line 485, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known
```

Am I doing something wrong? Did I miss something?

**Comment by tianon** [comment]
You're missing `--network` on your final `docker run` (which is what provides the DNS resolution).

**Comment by PiotrJustyna** [comment]
Ah, that was it, thanks!

```
docker run -it --network testnetwork --rm cassandra cqlsh some-cassandra
```

**Comment by himanshurobo** [comment]
My Cassandra App is running on a different ports. How to link cqlsh command with that port?
Getting Error :

`Traceback (most recent call last):
  File "/opt/cassandra/bin/cqlsh.py", line 2443, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/opt/cassandra/bin/cqlsh.py", line 2421, in main
    encoding=options.encoding)
  File "/opt/cassandra/bin/cqlsh.py", line 485, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/opt/cassandra/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known`
