### ISSUE TITLE
CASSANDRA_CLUSTER_NAME Failing

### ISSUE THREAD

**Issue by mpcontracting** [docker-library/cassandra#84]
When trying to set a custom cluster name with the CASSANDRA_CLUSTER_NAME variable, Cassandra fails to start up. This command:-

`docker run --name cassandra-1 -e CASSANDRA_CLUSTER_NAME="My New Cluster" -p=127.0.0.1:9042:9042 -v C:/Work/Cassandra/cassandra-1:/var/lib/cassandra -d cassandra:3.9`

fails to start and the following entries appear in the logs:-

`ERROR 14:31:33 Fatal exception during initialization
org.apache.cassandra.exceptions.ConfigurationException: Saved cluster name Test Cluster != configured name My New Cluster
        at org.apache.cassandra.db.SystemKeyspace.checkHealth(SystemKeyspace.java:935) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StartupChecks$9.execute(StartupChecks.java:325) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:112) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:196) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]`

The container starts up just fine if the cluster name is left as the default

**Comment by yosifkit** [comment]
Sounds like you already have data in the VM at `/C/Work/Cassandra/cassandra-1/`; which won't necessarily be the same as what is on your Windows host since the docker-toolbox VM only shares `C:\Users` by default.

**Comment by mpcontracting** [comment]
Nope, completely deleted those directories beforehand and they don't get recreated before the container dies.

I'm using the new docker for Windows 10 and have the whole C drive shared

**Comment by dwitherspoon** [comment]
I am getting the same results and I am using a data volume within my docker-compose file:

version: '2'
services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - my-backnet
    ports:
      - "7000"
      - "7199"
      - "9042"
      - "9160"
volumes:
  cassandra-data:
    driver: local
networks:
  my-backnet:
    driver: bridge

**Comment by tianon** [comment]
Closing, given that this appears to be resolved. :+1:
